[2025-03-08T04:05:04.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T04:05:04.251+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-08T04:05:01.413043+00:00 [queued]>
[2025-03-08T04:05:04.254+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-08T04:05:01.413043+00:00 [queued]>
[2025-03-08T04:05:04.254+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-08T04:05:04.260+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-08 04:05:01.413043+00:00
[2025-03-08T04:05:04.268+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-03-08T04:05:04.270+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'manual__2025-03-08T04:05:01.413043+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmprf6iz2os']
[2025-03-08T04:05:04.272+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask etl_process
[2025-03-08T04:05:04.296+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process manual__2025-03-08T04:05:01.413043+00:00 [running]> on host 83adae75723d
[2025-03-08T04:05:04.327+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T04:05:01.413043+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T04:05:01.413043+00:00'
[2025-03-08T04:05:04.327+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-08T04:05:04.334+0000] {etl-payments.py:31} INFO - üîπ Mengambil data dari database sumber...
[2025-03-08T04:05:10.832+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-08T04:05:20.929+0000] {etl-payments.py:36} INFO - ‚úÖ Data berhasil diambil!
[2025-03-08T04:05:20.931+0000] {etl-payments.py:38} INFO - üîπ Memproses data...
[2025-03-08T04:05:20.996+0000] {etl-payments.py:59} INFO - ‚úÖ Data berhasil dibersihkan!
[2025-03-08T04:05:22.722+0000] {etl-payments.py:71} INFO - üîç Data baru yang ditemukan: 0 record(s)
[2025-03-08T04:05:22.724+0000] {etl-payments.py:84} INFO - ‚úÖ Tidak ada data baru untuk dimasukkan hari ini.
[2025-03-08T04:05:22.724+0000] {etl-payments.py:88} INFO - ‚úÖ Proses ETL selesai!
[2025-03-08T04:05:22.803+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-08T04:05:22.817+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-08T04:05:22.818+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=manual__2025-03-08T04:05:01.413043+00:00, execution_date=20250308T040501, start_date=20250308T040504, end_date=20250308T040522
[2025-03-08T04:05:22.885+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-08T04:05:22.914+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-08T04:05:22.915+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
