[2025-03-08T02:37:54.627+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T02:37:54.632+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_lead_histories.etl_process manual__2025-03-08T02:37:51.296430+00:00 [queued]>
[2025-03-08T02:37:54.635+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_lead_histories.etl_process manual__2025-03-08T02:37:51.296430+00:00 [queued]>
[2025-03-08T02:37:54.635+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-08T02:37:54.642+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-08 02:37:51.296430+00:00
[2025-03-08T02:37:54.647+0000] {standard_task_runner.py:72} INFO - Started process 90 to run task
[2025-03-08T02:37:54.653+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_lead_histories', 'etl_process', 'manual__2025-03-08T02:37:51.296430+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/etl-lead-histories.py', '--cfg-path', '/tmp/tmpqnxs_ah8']
[2025-03-08T02:37:54.656+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask etl_process
[2025-03-08T02:37:54.702+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_lead_histories.etl_process manual__2025-03-08T02:37:51.296430+00:00 [running]> on host 58a7f6726a5c
[2025-03-08T02:37:54.746+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_lead_histories' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T02:37:51.296430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T02:37:51.296430+00:00'
[2025-03-08T02:37:54.747+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-08T02:37:54.791+0000] {etl-lead-histories.py:79} INFO - üîπ Memastikan tabel tujuan tersedia...
[2025-03-08T02:37:54.793+0000] {etl-lead-histories.py:39} INFO - üîπ Mengecek apakah tabel lead_histories_cleaned sudah ada di MySQL...
[2025-03-08T02:37:55.433+0000] {etl-lead-histories.py:75} INFO - ‚úÖ Tabel lead_histories_cleaned sudah tersedia atau berhasil dibuat!
[2025-03-08T02:37:55.436+0000] {etl-lead-histories.py:82} INFO - üîπ Mengambil data dari PostgreSQL...
[2025-03-08T02:38:42.620+0000] {etl-lead-histories.py:93} INFO - ‚úÖ Data berhasil diambil!
[2025-03-08T02:38:42.623+0000] {etl-lead-histories.py:96} INFO - üîπ Memproses data...
[2025-03-08T02:38:42.885+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-lead-histories.py:122 UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
[2025-03-08T02:38:42.920+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-lead-histories.py:123 UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
[2025-03-08T02:39:02.141+0000] {etl-lead-histories.py:136} INFO - ‚úÖ Data berhasil dibersihkan!
[2025-03-08T02:39:02.143+0000] {etl-lead-histories.py:139} INFO - üîπ Memeriksa data yang sudah ada di MySQL...
[2025-03-08T02:39:03.137+0000] {etl-lead-histories.py:149} INFO - üîç Data baru yang ditemukan: 268133 record(s)
[2025-03-08T02:39:04.429+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl-lead-histories.py", line 160, in etl_process
    cursor_target.executemany(sql_insert, cleaned_tuples)
  File "/home/airflow/.local/lib/python3.12/site-packages/pymysql/cursors.py", line 182, in executemany
    return self._do_execute_many(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymysql/cursors.py", line 205, in _do_execute_many
    v = values % escape(next(args), conn)
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
[2025-03-08T02:39:04.439+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_lead_histories, task_id=etl_process, run_id=manual__2025-03-08T02:37:51.296430+00:00, execution_date=20250308T023751, start_date=20250308T023754, end_date=20250308T023904
[2025-03-08T02:39:04.453+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-08T02:39:04.453+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 191 for task etl_process (not all arguments converted during string formatting; 90)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl-lead-histories.py", line 160, in etl_process
    cursor_target.executemany(sql_insert, cleaned_tuples)
  File "/home/airflow/.local/lib/python3.12/site-packages/pymysql/cursors.py", line 182, in executemany
    return self._do_execute_many(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymysql/cursors.py", line 205, in _do_execute_many
    v = values % escape(next(args), conn)
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
[2025-03-08T02:39:04.509+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-08T02:39:04.531+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T02:39:04.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
