[2025-01-29T04:11:23.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T04:11:23.681+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_movies_pipeline.load_to_staging manual__2025-01-29T04:06:11.410791+00:00 [queued]>
[2025-01-29T04:11:23.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_movies_pipeline.load_to_staging manual__2025-01-29T04:06:11.410791+00:00 [queued]>
[2025-01-29T04:11:23.684+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-29T04:11:23.763+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_staging> on 2025-01-29 04:06:11.410791+00:00
[2025-01-29T04:11:23.775+0000] {standard_task_runner.py:72} INFO - Started process 799 to run task
[2025-01-29T04:11:23.777+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_movies_pipeline', 'load_to_staging', 'manual__2025-01-29T04:06:11.410791+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/etl_movies_pipeline.py', '--cfg-path', '/tmp/tmp_ug99_yc']
[2025-01-29T04:11:23.779+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask load_to_staging
[2025-01-29T04:11:23.807+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_movies_pipeline.load_to_staging manual__2025-01-29T04:06:11.410791+00:00 [running]> on host 2fd33a817220
[2025-01-29T04:11:23.840+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_movies_pipeline' AIRFLOW_CTX_TASK_ID='load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T04:06:11.410791+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T04:06:11.410791+00:00'
[2025-01-29T04:11:23.841+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T04:11:23.875+0000] {logging_mixin.py:190} INFO - Data sebelum cleaning:
[2025-01-29T04:11:23.882+0000] {logging_mixin.py:190} INFO -                                              name  ... runtime
0                                     The Shining  ...   146.0
1                                 The Blue Lagoon  ...   104.0
2  Star Wars: Episode V - The Empire Strikes Back  ...   124.0
3                                       Airplane!  ...    88.0
4                                      Caddyshack  ...    98.0

[5 rows x 15 columns]
[2025-01-29T04:11:23.884+0000] {logging_mixin.py:190} INFO - Data setelah cleaning:
[2025-01-29T04:11:23.888+0000] {logging_mixin.py:190} INFO -                                              name  ... runtime
0                                     The Shining  ...   146.0
1                                 The Blue Lagoon  ...   104.0
2  Star Wars: Episode V - The Empire Strikes Back  ...   124.0
3                                       Airplane!  ...    88.0
4                                      Caddyshack  ...    98.0

[5 rows x 15 columns]
[2025-01-29T04:11:24.410+0000] {logging_mixin.py:190} INFO - Data tuple yang akan dimasukkan:
[2025-01-29T04:11:24.411+0000] {logging_mixin.py:190} INFO - [('The Shining', 'R', 'Drama', 1980, 'June 13, 1980 (United States)', 8.4, 927000.0, 'Stanley Kubrick', 'Stephen King', 'Jack Nicholson', 'United Kingdom', 19000000.0, 46998772.0, 'Warner Bros.', 146.0), ('The Blue Lagoon', 'R', 'Adventure', 1980, 'July 2, 1980 (United States)', 5.8, 65000.0, 'Randal Kleiser', 'Henry De Vere Stacpoole', 'Brooke Shields', 'United States', 4500000.0, 58853106.0, 'Columbia Pictures', 104.0), ('Star Wars: Episode V - The Empire Strikes Back', 'PG', 'Action', 1980, 'June 20, 1980 (United States)', 8.7, 1200000.0, 'Irvin Kershner', 'Leigh Brackett', 'Mark Hamill', 'United States', 18000000.0, 538375067.0, 'Lucasfilm', 124.0), ('Airplane!', 'PG', 'Comedy', 1980, 'July 2, 1980 (United States)', 7.7, 221000.0, 'Jim Abrahams', None, 'Robert Hays', 'United States', 3500000.0, 83453539.0, 'Paramount Pictures', 88.0), ('Caddyshack', 'R', 'Comedy', 1980, 'July 25, 1980 (United States)', 7.3, 108000.0, 'Harold Ramis', 'Brian Doyle-Murray', 'Chevy Chase', 'United States', 6000000.0, 39846344.0, 'Orion Pictures', 98.0)]
[2025-01-29T04:11:27.110+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 706, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'nan' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_movies_pipeline.py", line 61, in load_to_staging
    cursor.executemany(sql_insert, data_tuples)
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 481, in executemany
    return self.execute(stmt)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 106, in wrapper
    result = method(cnx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 714, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-01-29T04:11:27.133+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_movies_pipeline, task_id=load_to_staging, run_id=manual__2025-01-29T04:06:11.410791+00:00, execution_date=20250129T040611, start_date=20250129T041123, end_date=20250129T041127
[2025-01-29T04:11:27.151+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T04:11:27.151+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task load_to_staging (1054 (42S22): Unknown column 'nan' in 'field list'; 799)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 706, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'nan' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_movies_pipeline.py", line 61, in load_to_staging
    cursor.executemany(sql_insert, data_tuples)
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 481, in executemany
    return self.execute(stmt)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 106, in wrapper
    result = method(cnx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 714, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'nan' in 'field list'
[2025-01-29T04:11:27.183+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-29T04:11:27.214+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T04:11:27.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
